### ISSUE TITLE
No effect in 1.20.5 and later

### ISSUE THREAD

**Issue by yumunet** [Steveplays28/noisium#45] opened 2024-10-23 03:19 UTC
I tested with an Intel Core i5-3470 (4 cores 4 threads, base clock is 3.2 GHz) and cannot see the effect in Minecraft 1.20.5 and later.
I can see the effect in 1.20.4 and earlier.

I don't know if this is a bug of Noisium, if it is an issue dependent on my environment, if the world generation has been optimized in 1.20.5, or if it is a compatibility issue with Chunky.
However, I found it odd that it would not be effective with such a slow CPU.

# Test

Generate a 2000x2000 range with Chunky as in the benchmark on the Mod page and look at the logged times.

Fabric 0.16.7.
8GB memory is allocated (Argument: -Xms8192m -Xmx8192m -XX:+AlwaysPreTouch).
Video settings were lowered as much as possible (Render distance: 2, Simulation distance: 5, Grapchics: fast, Smooth lighting: off, Max FPS: 30, etc.).

PC Specs:
- OS: Windows 10
- CPU: i5-3470
- GPU: (integrated GPU)
- RAM: 16GB DDR3-1600
- Disk: SATA SSD

Do this step 3 times each.
1. Create world (Game mode: creative, Seed: 1)
2. Run `/tp @s 0 320 0 0 -90` to reduce what is rendered
3. Wait for CPU usage to drop to about 5%
4. Run the following commands to start world generation
    ```
    /chunky center 10000 10000
    /chunky radius 1000
    /chunky start
    ```

# Result

## 1.20.5

No effect.

without
1. 0:09:04
2. 0:09:02
3. 0:09:02

with Noisium 2.3.0 / Chunky 1.4.10
1. 0:09:02
2. 0:08:56
3. 0:08:57

## 1.20.4

Faster.

without
1. 0:09:16
2. 0:09:13
3. 0:09:15

with Noisium 2.3.0 / Chunky 1.3.146
1. 0:08:18
2. 0:08:20
3. 0:08:17

I also confirm that it is ineffective in 1.21.1 and effective in 1.20.1.

**Comment by Steveplays28** [comment] 2024-10-23 08:30
Hi, thanks for the detailed tests!
I've been meaning to set up a test bench to test futher optimisations, but I haven't gotten around to it.

I'll leave this issue open until I've explored various other optimisations and thoroughly tested them.

**Comment by yumunet** [comment] 2024-10-23 09:02
I see. Thanks for your reply!

**Comment by Steveplays28** [comment] 2024-12-18 14:51
Hi, to get back to you on this, I've done some testing on Linux with Spark using the async profiler, as well as with Chunky. The issue is that the generation time for (in my case) 1000 chunks radius is inconsistent and depends on a significant amount of factors, swaying the results.
I've updated the readme with Spark profiles using the async profiler engine. Nothing changed surrounding Noisium's optimisations in 1.20.5 besides the reduction of the amount of spawn chunks, so I'm closing this issue. If I implement new optimisations I'll update those benchmarks. Thanks for testing either way though.

**Closed as not planned by Steveplays28** 2024-12-18 14:51 UTC
Labels: documentation, invalid

**Comment by yumunet** [comment] 2024-12-18 15:53
Thank you.
Those spark profiles are with 1.20.1, will Noisium be effective in 1.20.5 and later? 
Can I trust this benchmarks of commit? (https://github.com/Steveplays28/noisium/tree/07037e87e32da3165c1ea17b54ae8b3d939c45d9?tab=readme-ov-file#minecraft-1205-and-up)

**Comment by Steveplays28** [comment] 2024-12-18 15:58
The benchmarks in that commit were all done on 1.20.1, I made a mistake when thinking they was made on 1.20.5, sorry.
Noisium should have a benefit in 1.20.5 and up, yes. You should be able to see similar changes as those in the Spark profiles.

**Comment by yumunet** [comment] 2024-12-18 16:35
Hmmm. So is it just a coincidence that in my testting it has no effect in 1.20.5 and later?

**Comment by Steveplays28** [comment] 2024-12-18 16:36
Yeah, the performance can depend on a lot of factors.

**Comment by yumunet** [comment] 2024-12-18 16:37
OK, thank you for replying!
