### ISSUE TITLE
Incompatibility with Lithium

### ISSUE THREAD

**Issue by Wesley1808** [Steveplays28/noisium#10] opened 2023-12-26 19:56 UTC
Hey! I've come across some strange chunk section related issues when running Noisium together with Lithium.
An example of this is that entities will be completely unable to detect if they're in water in certain chunk sections. 
Video showing this issue: https://streamable.com/4t71lf

What I'm suspecting is the cause of the issue here is that Lithium has this [optimization](https://github.com/CaffeineMC/lithium-fabric/blob/develop/src/main/java/me/jellysquid/mods/lithium/mixin/entity/collisions/fluid/EntityMixin.java) to shortcut fluid checks based on whether or not a chunk section contains any block of a certain flag. These values are maintained [here](https://github.com/CaffeineMC/lithium-fabric/blob/develop/src/main/java/me/jellysquid/mods/lithium/mixin/util/block_tracking/ChunkSectionMixin.java), but because of the below optimization in Noisium I believe there might be a chance this doesn't always get updated properly.

https://github.com/Steveplays28/noisium/blob/d407c928958ff7c65ac1277c325f0c4d987ba709/src/main/java/io/github/steveplays28/noisium/mixin/NoiseChunkGeneratorMixin.java#L112-L117

It might also be worth noting that this isn't always easy to reproduce and can take a while to find, and that it only really seems to happen in newly generated chunks (though that would probably make sense if this is the cause of it).

These blockstate flags are also used for other optimizations, so there's a good chance it may sometimes be breaking those aswell.

**Comment by Steveplays28** [comment] 2023-12-26 19:57
Hi Wesley, thanks for the report!
I'll take a look and see if I can reproduce/fix the issue.

**Comment by Steveplays28** [comment] 2023-12-26 20:14
I see the issue, there's a mixin injection into `setBlockState`, which I bypass by setting blocks in the palette directly.
I'll have to call that manually from Noisium's end if Lithium is present, or make a PR to Lithium to add compatibility.

**Comment by NotADinosaur** [comment] 2024-01-20 06:16
Hi, I/some friends have noticed this bug on my server after I added this mod to test its improvements, and with the water mobs dying it has started a "fish cult" lmao
I know this isn't useful to the issue but I thought it was funny :P

**Comment by Steveplays28** [comment] 2024-01-20 13:17
Hi NotADinosaur, that's a funny story. Last I heard, this issue was being worked on by a Lithium contributor.

**Comment by embeddedt** [comment] 2024-03-12 16:22
I'm curious - what is the performance delta of your microoptimization to `setBlockState`? At a cursory glance, the only logic you are skipping is decrementing the counters for the old block (presumably because you know it's always air), and I'm skeptical this saves enough time to be worth integrating with Lithium for.

**Comment by Steveplays28** [comment] 2024-03-12 16:26
@embeddedt Hi embeddedt,

This mod does indeed do a few micro-optimizations, though they aren't as good as I'd like them to be. Not even the main optimization is as good as I'd like it to be. That's for the future to improve on my end.
I did some exact testing with Uniter sometime ago, which showed performance benefits range between basically nothing and a few % per some big amount of chunks generated (iirc), and it's quite hardware-dependent.
In the grand scheme of things this does save a bit of time, which is better than nothing imo.

And, this bug is slightly critical for BuilderB0y's Big Globe, since it has the same issues. I don't currently have time to create a PR for this myself, but when I do have time I'll look into solutions in more detail. Lithium compat is quite important to me (and Builder is interested as well).
I appreciate you taking the time to investigate this issue.

**Comment by Steveplays28** [comment] 2024-04-14 17:56
I've released a fix for this in [`v2.0.2`](https://github.com/Steveplays28/noisium/releases/latest).

**Closed by Steveplays28** 2024-04-14 17:56 UTC
Labels: bug, compatibility, waiting for release

**Comment by GopsRay** [comment] 2024-04-19 15:11
1,Hlo Steveplays,does this new release of noisium mod 2.0.2 (1.20-1.20.1) completely fix this issue [ Incompatibilities
Lithium: submerged entities (such as fish and squids) occasionally suffocate in water and/or fall to the ground in water. All other features will work fine, just need to occasionally sacrifice a fish for performance.]??                                                                   2,And now Noisium is fully compatibile with lithium??                                                                                                                  3,Does your mod {CHANGE} or {ALTER} World generation?? Functions??                                                                                      4,please clarify my questions mainly q:3.

**Comment by Steveplays28** [comment] 2024-04-19 15:12
Hi GopsRay, the issue is completely fixed now. I forgot to update the readme. Thanks for reminding me about that.

**Comment by GopsRay** [comment] 2024-04-19 15:14
Its OK u made my potato laptop run smoother But can u pls answer this question Does your mod {CHANGE} or {ALTER} World generation?? Functions??

**Comment by Steveplays28** [comment] 2024-04-19 15:14
No, it doesn't alter world generation. Worlds generated with Noisium installed will look the exact same as without it.

**Comment by GopsRay** [comment] 2024-04-19 15:15
Thx Can I join ur discord

**Comment by Steveplays28** [comment] 2024-04-19 15:17
Sure, feel free to stop by. Link can be found at my GitHub profile and at my website.

**Comment by GopsRay** [comment] 2024-04-19 15:21
Noisium has full 1:1 parity with vanilla worldgen (worldgen without Noisium). oh ok I did't read this sorry for wasting ur time vanilla and noisium world generation are the same sorry for disturbing you.

**Comment by Steveplays28** [comment] 2024-04-19 15:22
@GopsRay No worries, have fun playing.

**Comment by XandarNull** [comment] 2024-08-01 05:01
> @GopsRay No worries, have fun playing.

What a chad mod dev, thanks for being nice and making this great mod
