### ISSUE TITLE
Mod Crashes on Neoforge 1.20.4

### ISSUE THREAD

**Issue by ModernGamingWorld** [Steveplays28/noisium#24] opened 2024-04-10 18:33 UTC
[latest.log](https://github.com/Steveplays28/noisium/files/14936282/latest.log)

**Comment by Steveplays28** [comment] 2024-04-10 18:34
Hi ModernGamingWorld, this issue is a duplicate of #21.
I'm working on this, thanks for checking out Noisium though.

**Closed as not planned by Steveplays28** 2024-04-10 18:34 UTC
Labels: bug, duplicate, crash
